scikit-learn import and comment fix
speechbrain/speechbrain pull request #1485
Opened 2022-06-28 10:28 UTC by underdogliu

This is related with issue #1484

I found in our diarization-related scripts and runners, we ask the users to install `sklearn`, instead of `scikit-learn`. `sklearn`, on pip, as pointed out in the issue, is a void package while `scikit-learn` is the library we want. Of course, in the python scripts, it is still imported as `import sklearn`.

Tests have been done via pip and conda. For conda actually, we can't even find `sklearn`.

Note: seems like this PR contains some un-necessary changes due to my [black](https://github.com/psf/black) accent plugin in my vscode....if necessary I can check them out.

2022-06-28 19:20 UTC, anautsch commented
Thank you @underdogliu :D

Please run linters & update this one too (hope I didn't miss it)
https://github.com/speechbrain/speechbrain/blob/1b5811cf1c60654723ff0f0b8b112ee832a6cdf3/recipes/UrbanSound8k/SoundClassification/train.py#L29

2022-06-28 19:37 UTC, nauman-daw requested changes
Thanks @underdogliu  
Kindly make the necessary changes to pass all the tests. They are mostly minor syntax updates. 
These changes looks good to me.
 @mravanelli   this PR can be merged once all the tests are passed.

2022-08-30 04:16 UTC, underdogliu commented
@mravanelli Some of my changes on voxceleb2 results today are merged with this PR, as we discussed. Just for your information. I would not open another PR.

2022-08-30 08:56 UTC, anautsch commented on recipes/VoxCeleb/SpeakerRec/hparams/verification_ecapa.yaml
> +data_folder: /data/xuechen/corpus/voxceleb1
placeholder :)

2022-08-30 08:57 UTC, anautsch commented on recipes/VoxCeleb/SpeakerRec/hparams/verification_ecapa.yaml
> +pretrain_path: results/ecapa_augment/1986/save/CKPT+2022-08-23+14-22-41+00
please use the earlier one

2022-08-30 09:10 UTC, anautsch commented on recipes/VoxCeleb/SpeakerRec/hparams/verification_ecapa.yaml
> +# score_norm: s-norm  # z-norm t-norm s-norm (uncomment to enable it)
to be discussed

2022-09-27 08:11 UTC, Adel-Moumen commented
Hello, 

Is there any news on this PR, please? 😃

2022-11-02 16:17 UTC, mravanelli commented
Hi @underdogliu, could you pelease fix the linters and the faling tests?

2022-11-03 12:03 UTC, underdogliu commented
@mravanelli @anautsch all tests have been passed.

2022-11-03 13:43 UTC, mravanelli approved these changes

2022-11-03 13:43 UTC, mravanelli commented
Thank you @underdogliu!

2022-11-03 13:43 UTC, merged