Add CTC recipe to AISHELL-1
speechbrain/speechbrain pull request #1576
Opened 2022-09-14 18:04 UTC by BenoitWang

Hi @mravanelli @TParcollet , this PR adds a typical CTC-wav2vec recipe to AISHELL-1.
Test CER: 5.06%
Dev CER: 4.52%

Some points:
1. [chinese-wav2vec2-large](https://huggingface.co/TencentGameMate/chinese-wav2vec2-large) (from Tencent) is used which is pretrained on 10k hours Chinese data
2. [bert-base-chinese](https://huggingface.co/bert-base-chinese) is used as the tokenizer, ctc is trained on chars
3. In `prepare.py`, `pandas` is not necessary to be used to generate csv, so it is deleted together with some unused variables.

2022-09-14 21:00 UTC, TParcollet commented
Huge ! Is this comparable to the SOTA around?

2022-09-14 22:04 UTC, BenoitWang commented
Hi @TParcollet , I think it's good for a system pure-CTC/greedy/without LM. 
Hybrid models from espnet got better CER:

model | Test CER | Dev CER | LM
-- | -- | -- | --
our ctc-wav2vec | 5.06% | 4.52% | No
espnet: branchformer-beam10-ctc0.4 | 4.4% | 4.1% | No
espnet: conformer-beam20-ctc0.3 | 4.9% | 4.5% | No

2022-09-14 22:32 UTC, TParcollet commented
I see, not bad, but we use extra pre-training while they don't, correct ?

2022-09-14 22:52 UTC, BenoitWang commented
Yes exact. Fair enough, but their [branchformer](https://arxiv.org/pdf/2207.02971.pdf) is quite something according to the results.

2022-09-19 07:08 UTC, anautsch requested changes
Hi @BenoitWang minor details only.

The yaml file combines related hparam files well; as is for the train script.

Is the AISHELL-1 prepare script completely stripped of the extra dependency to `pandas` for all its recipes? 
(not a bad thing to reduce dependencies, although pandas is neat, - just asking - pandas is not in the SB requirements and neither it is explicitly stated fo AISHELL-1, so it's a good catch)

2022-09-19 14:41 UTC, BenoitWang commented
Hi @anautsch thanks for the review, the fix is done. And yes that's why I want to reduce pandas, it is only used to generate csv for all the recipes.

2022-09-19 15:17 UTC, anautsch approved these changes

2022-09-19 15:27 UTC, TParcollet commented on recipes/AISHELL-1/ASR/CTC/README.md
> +Make sure to have "transformers" installed.
please add an extra_requirements.txt file with transformer in it :-)

2022-09-19 15:27 UTC, TParcollet commented on recipes/AISHELL-1/ASR/CTC/README.md
> +- To be added
Must be added before merging, I guess?

2022-09-19 15:29 UTC, TParcollet commented on recipes/AISHELL-1/ASR/CTC/prepare.py
> +../../prepare.py
Hey, the naming convention of the file is not equivalent to other recipes, please have a look at the name and just rename the file accordingly.

2022-09-19 15:31 UTC, TParcollet commented on recipes/AISHELL-1/ASR/CTC/train_with_wav2vec.py
> +        tokens_bos = torch.LongTensor([hparams["bos_index"]] + (tokens_list))
If not mistaken, bos and Eos tokens are not used, they could be removed from the text_pipeline.

2022-09-26 07:32 UTC, anautsch approved these changes

2022-10-06 15:27 UTC, BenoitWang commented
Hi @TParcollet @anautsch @Adel-Moumen,

Thank you all for the reviews and tests! The HF link is added, here's a brief summary of the PR:
1. add a CTC recipe
2. fix naming problems
3. fix dynamic batching conflicts for seq2seq & transformer recipes

2022-10-07 13:55 UTC, anautsch commented
lgtm.

Tested recipes in `--debug` mode & the wav2vec2 with ddp.

---

Side note: we have an internal issue with `--debug` and eval checkpointing - this comes clear when running this transformer wav2vec2 recipe - here's the relevant log
```
   asr_brain.evaluate(
  File "speechbrain/core.py", line 1260, in evaluate
    self.on_evaluate_start(max_key=max_key, min_key=min_key)
  File "train_with_wav2vect.py", line 272, in on_evaluate_start
    ckpt = sb.utils.checkpoints.average_checkpoints(
  File "speechbrain/utils/checkpoints.py", line 1174, in average_checkpoints
    return averager(parameter_iterator)
  File "speechbrain/utils/checkpoints.py", line 1080, in average_state_dicts
    raise ValueError("No state dicts to average.")
ValueError: No state dicts to average.
```

2022-10-07 13:57 UTC, merged