Recipe for SEP-28k dataset
speechbrain/speechbrain pull request #2574
Opened 2024-06-18 08:15 UTC by IliasMAOUDJ

## What does this PR do?

This PR adds the SEP-28k dataset (https://github.com/apple/ml-stuttering-events-dataset) to the list of recipes with the partitioning suggested in https://rdcu.be/dK8Ei (https://github.com/th-nuernberg/ml-stuttering-events-dataset-extended).
Additionally, we provide a repository to download the deleted podcast "StrongVoices" and "IStutterSoWhat", so that every researcher can have access to the full dataset.
We provide a minimal working example for training.

<details>
  <summary><b>Before submitting</b></summary>

- [X] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [X] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [X] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [X] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [X] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [X] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [ ] Review the self-review checklist to ensure the code is ready for review

</details>

2024-06-19 15:49 UTC, IliasMAOUDJ commented
unittests and doctests pass succesfully but linters fails on files that I didn't change.

2024-06-25 12:22 UTC, asumagic commented
Note: CI is currently failing overall, when #2581 is merged (will notify) do update the fork branch against `develop`.

2024-06-25 12:31 UTC, asumagic commented
> Note: CI is currently failing outside of the PR, when #2581 is merged (will notify) do update the fork branch against `develop`.

Done and it seems to work, you can now do that.

2024-07-02 08:20 UTC, asumagic commented
> > Note: CI is currently failing outside of the PR, when #2581 is merged (will notify) do update the fork branch against `develop`.
> 
> Done and it seems to work, you can now do that.

Sorry, needs to be done again, the fix had broken again.

2024-07-02 13:04 UTC, IliasMAOUDJ commented
Thank you for updating.

2025-01-12 15:07 UTC, pplantinga requested changes
Thanks for adding this recipe for a new task, will be great to have in the toolkit.

I was not able to run this recipe yet, when I tried, I got `FileNotFoundError: [Errno 2] No such file or directory: 'manifests/train.csv'` which suggests that the recipe is not creating the manifest files as our recipes typically do. Please add code to automatically create the manifest, unless I'm somehow running the recipe wrongly.

I will try to run again once the comments here are addressed.

2025-01-12 15:07 UTC, pplantinga commented on recipes/SEP-28k/train.py
> +        self.y_true_binary = torch.tensor(()).to("cuda:0")
We have [BinaryMetricStats](https://speechbrain.readthedocs.io/en/latest/API/speechbrain.utils.metric_stats.html#speechbrain.utils.metric_stats.BinaryMetricStats) which may be an easier way of doing what you're computing here, though I don't think it does confusion matrix yet. You could use the class to store the predictions and pass to scikit-learn to get confusion matrix.

2025-01-12 15:07 UTC, pplantinga commented on recipes/SEP-28k/train.py
> +        self.y_true_binary = torch.tensor(()).to("cuda:0")
But if you keep it as-is, use `self.device` instead of `"cuda:0"`

2025-01-12 15:07 UTC, pplantinga commented on recipes/SEP-28k/train.py
> +        return (EpId, int(ClipId)), audio.squeeze()
```suggestion
        return (EpId, int(ClipId)), waveform.squeeze()
```

2025-01-14 16:07 UTC, IliasMAOUDJ commented
Thank you for your review. All comments were addressed. Hopefully the changes can be accepted.

Concerning the task name, I suggest "Stuttering-Detection" which is straightforward and precise. It can be considered as a subcategory of Fluency/Speech Impairments if the toolkit ever welcome other datasets for specific impairments (which can be produced by various pathologies such as Parkinson's Disease, Alzheimer's Disease, etc).

2025-01-14 19:33 UTC, pplantinga commented on recipes/VoxLingua107/lang_id/README.md
> -
Removed from this PR

2025-01-14 19:33 UTC, pplantinga commented on speechbrain/inference/diarization.py
> +            return results
Removed from this PR

2025-01-14 19:58 UTC, pplantinga approved these changes
Okay, I've made a few fixes, and the recipe seems to work now, recipe tests and all.

Please make sure the recipe is still running according to your expectations and address any lingering questions. Then this is ready for merge.

2025-01-14 19:58 UTC, pplantinga commented on recipes/SEP-28k/stuttering-detection/README.md
> +Note that this is a minimal working example. The model and training parameters should be modified accordingly.
Do you have results to share with a bigger/better model? A brief discussion of results achieved with the recipe is often included in the README.

2025-01-16 09:40 UTC, IliasMAOUDJ commented on recipes/SEP-28k/stuttering-detection/README.md
> +Note that this is a minimal working example. The model and training parameters should be modified accordingly.
Thanks for your fixes, I ran the recipe after your changes and it works as intended. You can merge it.

I have not developed a better model compared to the literature yet, however I can point to papers dealing with this task. 
I am using the dataset for research purpose but not to develop "a better model", this may involve future development for the recipe, we can discuss it in private if you'd like more information.

2025-01-16 14:29 UTC, merged