Add adapter tutorial
speechbrain/speechbrain pull request #2707
Opened 2024-10-01 23:45 UTC by pplantinga

Closes #2698

This PR adds a tutorial for adapters.

While writing it, I discovered that the adapters implementation does not play very nice with `Pretrainer`, as the changes to the model structure prevent loading the pretrained weights. Thus in addition to the tutorial, this PR makes a small change to the `speechbrain.nnet.adapters.AdaptedModel` class that allows one to manually insert the adapters at a later time, which would typically look like:

```python
pretrainer.collect_files()
pretrainer.load_collected()
hparams["model"].insert_adapters()
```

2024-10-07 09:59 UTC, TParcollet requested changes
Thanks @pplantinga ! I only have two minor changes:
1. Could you summarize at the very beginning of the tutorial how to add an adapter to the yaml? This could be useful to our users that do not want to go into all the details. Like maybe just the piece of yaml code showing the decoration of the module.
2. In know that we must go with python modification of the yaml so it works in a notebook, but that *may* be confusing to some. Could you put, at the end of the tutorial, the full yamls? 

Once this is changed, and if @asumagic is happy, then i'll merge.

2024-10-07 09:59 UTC, TParcollet commented on speechbrain/nnet/adapters.py
> +    manual_adapter_insertion: bool
This docstring is a bit unclear to me.

2024-10-08 11:51 UTC, asumagic requested changes

2024-10-08 11:51 UTC, asumagic commented on docs/tutorials/nn.rst
> +.. rubric:: `🔗 # Neural Network Adapters for faster low-memory fine-tuning <nn/neural-network-adapters.html>`_
```suggestion
.. rubric:: `🔗 Neural Network Adapters for faster low-memory fine-tuning <nn/neural-network-adapters.html>`_
```

2024-10-08 11:51 UTC, asumagic commented on docs/tutorials/nn.rst
> +TThis tutorial covers the SpeechBrain implementation of adapters such as LoRA. This includes how to integrate either SpeechBrain implemented adapters, custom adapters, and adapters from libraries suc
```suggestion
This tutorial covers the SpeechBrain implementation of adapters such as LoRA. This includes how to integrate either SpeechBrain implemented adapters, custom adapters, and adapters from libraries such as PEFT into a pre-trained model.
```

2024-10-08 11:51 UTC, asumagic commented on docs/tutorials/nn/neural-network-adapters.ipynb
Should run `tutorial-cell-update.py`, see https://github.com/speechbrain/speechbrain/tree/develop/docs#integration-in-documentation

This should automatically add the header and footer for colab + the SB citation we have on every tutorial.

2024-10-08 11:51 UTC, asumagic commented on docs/tutorials/nn/neural-network-adapters.ipynb
Install step is broken, should specify `!python -m pip install -e speechbrain` not `.`

2024-10-08 11:51 UTC, asumagic commented on docs/tutorials/nn/neural-network-adapters.ipynb
Should indicate somewhere that CUDA should be available (and so the proper runtime on Colab should be selected, if running from that).

The `train.py` command otherwise fails, and `--device=cpu` is too slow (hours).

2024-10-08 11:51 UTC, asumagic commented on docs/tutorials/nn/neural-network-adapters.ipynb
I'll keep a Colab running to make sure it's working properly and will update on that front. In the mean time, pushing this review. Seemed fine for me otherwise.

2024-10-08 12:34 UTC, asumagic commented
Ah, yeah, this is also plagued with the issue where creating a `speechbrain` directory means that `import`s later in the notebook are relative to the wrong directory (`./speechbrain/` instead of `./speechbrain/speechbrain`). Might need a workaround or rename.

2024-10-08 19:11 UTC, pplantinga commented on docs/tutorials/nn/neural-network-adapters.ipynb
I have run this now, thanks

2024-10-08 19:11 UTC, pplantinga commented on docs/tutorials/nn/neural-network-adapters.ipynb
Ah, good catch. I had only run this locally, but have now run it on colab and fixed the imports

2024-10-08 19:11 UTC, pplantinga commented on docs/tutorials/nn/neural-network-adapters.ipynb
Good point, added

2024-10-08 19:12 UTC, pplantinga commented on speechbrain/nnet/adapters.py
> +    manual_adapter_insertion: bool
Good to know, hope it is clear now.

2024-10-08 19:14 UTC, pplantinga commented
> * Could you summarize at the very beginning of the tutorial how to add an adapter to the yaml? This could be useful to our users that do not want to go into all the details. Like maybe just the piece of yaml code showing the decoration of the module.

Good idea. I have added a TL;DR section at the beginning with just the yaml snippet, for those who are looking for this.

> * In know that we must go with python modification of the yaml so it works in a notebook, but that _may_ be confusing to some. Could you put, at the end of the tutorial, the full yamls?

The yamls are available in the file browser after running the tutorial. Putting it in the notebook itself may be overwhelming since they are quite long.

2024-10-09 08:57 UTC, asumagic approved these changes

2024-10-09 09:49 UTC, merged