Streaming recipe for BestRQ
speechbrain/speechbrain pull request #2790
Opened 2024-12-21 18:23 UTC by Chaanks

## What does this PR do?

Add streaming recipe for BestRQ on LibriSpeech

<details>
  <summary><b>Before submitting</b></summary>

- [x] Did you read the [contributor guideline](https://speechbrain.readthedocs.io/en/latest/contributing.html)?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing [tests](https://github.com/speechbrain/speechbrain/tree/develop/tests) pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Does your code adhere to project-specific code style and conventions?

</details>

## PR review

<details>
  <summary>Reviewer checklist</summary>

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified
- [x] Confirm that the changes adhere to compatibility requirements (e.g., Python version, platform)
- [x] Review the self-review checklist to ensure the code is ready for review

</details>

2024-12-21 18:23 UTC, Chaanks commented
@Adel-Moumen

2024-12-22 13:51 UTC, Adel-Moumen commented on recipes/LibriSpeech/self-supervised-learning/BEST-RQ/hparams/BEST-RQ-streaming.yaml
> +output_folder: !ref results/<seed>/<run_name>
I think you should rename `run_name` to `experiment_name`. I would also suggest `output_folder` to be `output_folder: !ref results/<experiment_name>/<seed>/` to remain consistent with some other yamls that already introduced this feature

2024-12-22 13:51 UTC, Adel-Moumen commented on recipes/LibriSpeech/self-supervised-learning/BEST-RQ/train.py
> -    with open(hparams_file, encoding="utf-8") as fin:
why?

2025-01-12 13:46 UTC, TParcollet requested changes
Thanks @Chaanks, the requested changes are very minimal. Once done, we can merge it.

2025-01-12 13:46 UTC, TParcollet commented on recipes/LibriSpeech/self-supervised-learning/BEST-RQ/hparams/BEST-RQ-streaming.yaml
> +# Model: Best-RQ
A word about streaming

2025-01-12 13:46 UTC, TParcollet commented on recipes/LibriSpeech/self-supervised-learning/BEST-RQ/hparams/BEST-RQ-streaming.yaml
> +train_num_buckets: 400
That seems to be a massive number of bucket for Librispeech, maybe 200 instead?

2025-01-12 13:46 UTC, TParcollet commented on recipes/LibriSpeech/self-supervised-learning/BEST-RQ/hparams/BEST-RQ-streaming.yaml
> +dynchunktrain_config_sampler: !new:speechbrain.utils.dynamic_chunk_training.DynChunkTrainConfigRandomSampler # yamllint disable-line rule:line-length
Wrong indentation (see CI)

2025-01-12 13:46 UTC, TParcollet commented on recipes/LibriSpeech/self-supervised-learning/BEST-RQ/train.py
> +                num_to_keep=10,
Why 10? This is fairly costly storage-wise. can't we keep 4?

2025-05-23 15:03 UTC, TParcollet approved these changes
LGTM.

2025-05-28 17:58 UTC, merged