catch and fix file encoding
speechbrain/speechbrain pull request #632
Opened 2021-04-07 19:01 UTC by flozi00

This PR catches an error I recognized while running commonvoice

2021-04-08 09:34 UTC, TParcollet commented
@aheba could you have a look at the change made on SentencePiece on this PR ? The one on CV LGTM.

2021-04-08 09:54 UTC, Gastron commented
Hey, thanks for the PR!

Hardcoding UTF-8 might be problematic for core library code (dataio, tokenizer): what if someone needs to use a different encoding? Though I am not sure if we have any defined stance on encodings in SpeechBrain. [This  post](http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html) lists different strategies for dealing with text files. Before this PR, the library code doesn't specify an encoding explicitly, so Python looks at the OS defaults and the PYTHONIOENCODING environment variable (this is the `Files in a typical platform specific encoding` strategy, new strategy would be `Files in a consistent, known encoding`). Seems like the PR is really about the Common Voice recipe, though, am I right, @flozi00 ? Any thoughts on this? I feel like this is a bigger question.

Hardcoding an encoding for a particular recipe seems natural, when that dataset has a consistent encoding.

2021-04-08 09:56 UTC, TParcollet commented
I don't really know if CV is consistent on his encoding scheme though .....

2021-04-08 10:07 UTC, flozi00 commented
Could we pass the encoding scheme from the hyperparameters ?
The german commonvoice is not 100% clean and contains characters from france and greek too, that'swhy the default encoding crashed.
Retrieving the encoding from system isn't clean solution, if I want to train other languages too, then I would have to change system settings for each training.

2021-04-08 10:09 UTC, TParcollet commented
Sure, simply create a yaml variable and get it when calling commonvoice_prepare with hparams["your_variable"].

2021-04-08 10:15 UTC, flozi00 commented
Can we set this variable global ?
So we don't need to pass at every function call, just import it from somewhere. Like this:

file_utils.py
`file_encoding = "utf-8"`

Recipe:
```
from speechbrain.utils.file_utils import file_encoding
file_encoding = "my encoding" #override default value
```

In core of the library:
```
from speechbrain.utils.file_utils import file_encoding

open(filepath, "r", encoding=file_encoding)
```

2021-04-08 12:44 UTC, Gastron commented
Without explicitly specifying the encoding, Python3 looks at a few environment sources to determine which encoding to expect. Doesn't that achieve the same globally specified encoding, but keep the ability to change the global default?

2021-04-09 17:43 UTC, flozi00 commented
The way with Environment variables has some more limitations I think. If you are okay with the global config variable I would start at weekend with doing it. Just tell me which way you want to go, Python environment variables or global variable in code :)

2021-04-10 21:57 UTC, mravanelli commented
Thank you @flozi00. What do you think @Gastron about this change?

2021-04-12 16:38 UTC, Gastron commented
I like the environment variable approach (i.e. keeping the core library as is.), because it uses the Python standard approach. I'm happy to hear more elaboration on the possible downsides of that approach, I can surely be missing something. But if nothing else, I'd like to go with the current environment variable approach and just change the recipe in this PR.

2021-04-20 08:43 UTC, Gastron requested changes
Added formal review, but just basically reiterates my earlier comment.

2021-04-20 08:43 UTC, Gastron commented on speechbrain/dataio/dataio.py
> +    with open(csv_path, newline="", encoding="utf-8") as csvfile:
Let's just discard this change

2021-04-20 08:43 UTC, Gastron commented on speechbrain/tokenizers/SentencePiece.py
> +        annotation_file = open(self.annotation_train, "r", encoding="utf-8")
Again, just discard these.

2021-04-20 08:43 UTC, Gastron commented on speechbrain/tokenizers/SentencePiece.py
> +        text_file = open(self.text_file, "w+", encoding="utf-8")
And this

2021-04-20 08:43 UTC, Gastron commented on speechbrain/tokenizers/SentencePiece.py
> +            if len(row) > index_label:
This seems to be a silent skip for empty CSV lines or lines which have missing columns. Feels like this should rather be fixed at the CSV creation stage, right? I feel like a silent skip should maybe only happen for empty lines. But this is a minor comment.

2021-04-20 08:43 UTC, Gastron commented on recipes/CommonVoice/common_voice_prepare.py
> +    loaded_csv = open(orig_tsv_file, "r", encoding="utf-8").readlines()[1:]
Keep this if Common Voice is reliably utf-8.

2021-04-25 19:20 UTC, closed without merging